name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Vue.JS project to Github Pages
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          lfs: false

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Publish to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}